### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/rooms/add/new-room
Content-Type: application/json

{
  "roomType": "single bed",
  "roomPrice": 200
}
